apiVersion: v1
kind: Service
metadata:
  name: demo-webapp-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080